# Generated by Django 3.1.1 on 2020-09-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(max_length=30)),
                ('blog_content', models.CharField(max_length=30)),
                ('blog_date', models.DateTimeField()),
                ('blog_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
