# Generated by Django 3.1.1 on 2020-09-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0009_blog_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_img',
            new_name='blog_cover',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_heading',
            new_name='blog_tittle',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_date',
        ),
    ]
