# Generated by Django 3.1.1 on 2020-09-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0010_auto_20200909_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_tittle',
            field=models.CharField(max_length=40),
        ),
    ]
