# Generated by Django 3.1.1 on 2020-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0012_auto_20200909_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.CharField(default=5, max_length=120),
            preserve_default=False,
        ),
    ]
