# Generated by Django 3.1.1 on 2020-09-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0013_blog_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=models.CharField(max_length=70),
        ),
    ]
