# Generated by Django 3.1.1 on 2020-09-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0018_auto_20200912_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_tittle',
            field=models.CharField(max_length=70),
        ),
    ]
