# Generated by Django 3.1.1 on 2020-09-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0020_auto_20200912_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_tittle',
            field=models.CharField(max_length=40),
        ),
    ]
