# Generated by Django 3.1.1 on 2020-09-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0021_auto_20200912_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_cover',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
    ]
