# Generated by Django 3.1.1 on 2020-09-12 05:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0022_auto_20200912_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_cover',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.CharField(default=3, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.CharField(choices=[('mostPopular', 'Most Popular'), ('recentPost', 'Recent Post')], default='mostPopular', max_length=11),
        ),
    ]
